### ISSUE TITLE
Update with latest version of slate

### ISSUE THREAD

**Issue by mattmazzola** [CrossLead/slate-dts#2]
I'm not sure if there was a major API change in slate recently but it appears these type definitions don't have declarations for the `Value` which is one of the core objects.  The repo says last update was 2 months ago so I thought perhaps it's just out of date.

Example:
```
import { Value } from 'slate'
```
> Module ''slate'' has no exported member 'Value'.

And from looking at the .d.ts file I don't see it either although Document, Range, etc are there.

It seems like this was created as unofficial support as I found it from here:
https://github.com/ianstormtaylor/slate/issues/560

But if it's an easy thing to re-run a script and get new types it might be worth it.

**Comment by mattmazzola** [comment]
Perhaps `Value` used to be `State`:
https://github.com/CrossLead/slate-dts/blob/master/packages/slate/slate.d.ts#L2071

**Comment by bsouthga** [comment]
@mattmazzola just re-ran the script and updated the typings to everythign as of `0.31.5` -- just a note I've decided against publishing, so just including the typings in your tsconfig is the way to go.

**Comment by mattmazzola** [comment]
Ok, thanks!
